# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome ')),
                ('end', models.CharField(max_length=200, verbose_name='Endereço ')),
                ('fone', models.CharField(max_length=200, verbose_name='Fone ')),
            ],
        ),
    ]
