# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome ')),
                ('cpf', models.CharField(max_length=200, verbose_name='CPF ')),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
