# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nome_Candidato', to='votacao.Candidato')),
                ('eleitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nome_Eleitor', to='votacao.Eleitor')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='votacao.Token')),
            ],
        ),
    ]
