# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0005_votar'),
    ]

    operations = [
        migrations.AddField(
            model_name='votar',
            name='branco',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
