# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0006_votar_branco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Vaga: ')),
            ],
        ),
        migrations.AlterField(
            model_name='votar',
            name='candidato',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nome_Candidato', to='votacao.Candidato'),
        ),
        migrations.AlterField(
            model_name='votar',
            name='eleitor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nome_Eleitor', to='votacao.Eleitor'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='vaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nome', to='votacao.Vaga'),
        ),
    ]
