# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0007_auto_20171120_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nome', to='votacao.Eleitor'),
        ),
    ]
